export const data = [
	{
		pid: 1,
		pname: 'zzz 1Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 800.0,
		pimg: 'https://www.recipetineats.com/wp-content/uploads/2014/06/Stir-Fried-Noodles-Build-Your-Own-1.jpg',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 2,
		pname: 'xxx 2Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 700.0,
		pimg: 'https://www.thespruceeats.com/thmb/Cm5ndEKKEbEQtGxMrOK0jnQjIYk=/1500x844/smart/filters:no_upscale()/shanghai-stir-fried-noodles-4118753-12_preview-5b2927ba43a103003791a8ce.jpeg',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 3,
		pname: 'yyy 3Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 545,
		pimg: 'https://www.eatperu.com/wp-content/uploads/2019/12/tallarin-saltado-recipe-peruvian-stirfry-noodles.jpg',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 4,
		pname: '4Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 1200.0,
		pimg: 'https://i0.wp.com/eatwhattonight.com/wp-content/uploads/2016/10/Soy-Sauce-Noodles_3.jpg',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 5,
		pname: '5Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 1000.0,
		pimg: 'https://omnivorescookbook.com/wp-content/uploads/2015/12/1512_15-Minute-Fried-Noodles_003-1.jpg',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 6,
		pname: '6Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 1100.0,
		pimg: 'https://placeimg.com/602/480/any',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 7,
		pname: '7Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 1020.0,
		pimg: 'https://placeimg.com/601/480/any',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 8,
		pname: '8Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 200.0,
		pimg: 'https://placeimg.com/606/480/any',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 9,
		pname: '9Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 100.0,
		pimg: 'https://placeimg.com/650/480/any',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 10,
		pname: '10Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 10.0,
		pimg: 'https://placeimg.com/651/480/any',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 11,
		pname: '11Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 900.0,
		pimg: 'https://placeimg.com/642/480/any',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 12,
		pname: '12Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 980.0,
		pimg: 'https://placeimg.com/643/480/any',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 13,
		pname: '13Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 1500.0,
		pimg: 'https://placeimg.com/644/480/any',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 14,
		pname: '14Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 170.0,
		pimg: 'https://placeimg.com/645/480/any',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 15,
		pname: '15Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 888.0,
		pimg: 'https://placeimg.com/641/480/any',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 16,
		pname: '16Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 999.0,
		pimg: 'https://placeimg.com/630/480/any',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 17,
		pname: 'www 17Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 345.0,
		pimg: 'https://placeimg.com/620/480/any',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 18,
		pname: '18Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 534.0,
		pimg: 'https://placeimg.com/510/480/any',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 19,
		pname: '19Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 268.0,
		pimg: 'https://placeimg.com/600/480/any',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 20,
		pname: '20Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 1250.0,
		pimg: 'https://placeimg.com/640/480/any',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
	{
		pid: 21,
		pname: '21Lorem ipsum',
		pdesc: 'dolor sit amet dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt',
		pprice: 1350.0,
		pimg: 'https://placeimg.com/350/480/any',
		pstore: 'Lorem ipsum',
		pcategory: 'ipsum dolor',
	},
];
